environment:
  matrix:
    # Visual Studio 2015
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      SRC_FOLDER: src/VS2015

    # Visual Studio 2017
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017 RC
      SRC_FOLDER: src/VS2017

before_build:
  - nuget restore